import React, { useRef, useEffect } from 'react';
import * as THREE from 'three';

/**
 * GENERATED BY CHATGPT, AT MY REQUEST
 * YAY OPENSOURCE
*/
const WebGLScene = () => {
  const containerRef = useRef();

  useEffect(() => {
    // Create a scene
    const scene = new THREE.Scene();
    // Create a camera
    const camera = new THREE.PerspectiveCamera(75, window.innerWidth / window.innerHeight, 0.1, 1000);
    camera.position.z = 5;

    // Create a renderer
    const renderer = new THREE.WebGLRenderer();
    renderer.setSize(window.innerWidth, window.innerHeight);

    // This line is needed because we dont want an infinite list of growing windows, obviously
    containerRef.current.textContent=''; // Re-eval later if there is a better way to do this

    containerRef.current.appendChild(renderer.domElement);
    console.log(containerRef.current)
    // Create a cube and add it to the scene
    const geometry = new THREE.BoxGeometry();
    const material = new THREE.MeshBasicMaterial({ color: 0x6644ff });
    const cube = new THREE.Mesh(geometry, material);
    scene.clear();
    scene.add(cube);

    // Animation function
    const animate = () => {
      requestAnimationFrame(animate);

      // Rotate the cube
      cube.rotation.x += 0.01;
      cube.rotation.y += 0.01;

      // Render the scene
      renderer.render(scene, camera);
    };

    animate();
  }, []);

  return <div ref={containerRef} />;
};

export default WebGLScene;